version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strapi-examples-chessecake
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: strapi-examples-chessecake
  chessecakes:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 1337:1337
    environment:
      NODE_ENV: production
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: strapi-examples-chessecake

volumes:
  mongo:
    driver: local
